### ISSUE TITLE
Can I Run THis On My VPS

### ISSUE THREAD

**Issue by DevHanza** [samsesh/GoogleConsole_CPUminer#1]
Can I Run This Script On Ubuntu 18.04 LTS Private Virtual Machine? Please Respond to this issues soon as possible.

**Comment by samsesh** [comment]
Yes , you can run on any vps (debain based)

**Comment by DevHanza** [comment]
> Yes , you can run on any vps (debain based)

**Is It Legal and allowed to use bitcoin minning?**

**Comment by samsesh** [comment]
yes
